_target_: src.datamodule.gotcha_PL_datamodule_v2.GotchaDataModule

defaults:
  - _self_
  - transforms: gotcha

batch_size: 32 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
num_workers: 0
pin_memory: True
train_val_split: [0.8, 0.2]
datasets:
  main:
    _target_: src.datamodule.components.gotcha_dataset_v2.GotchaDataset
    csv_path: "/home/benik/Documents/Gotcha/first_drone_exp_filtered/gt_with_recs_stats_df_100.csv"
    weighted_sampling: True
    build_from_raw_data: False
    dataset_keys: #labels mapping in the dataframe
      df_raw_data_sample_key: "full_path" # key in the dataset for the path of the sample
