_target_: src.datamodule.isar_datamodule.ISARDataModule

defaults:
  - _self_
  - transforms: defaults.yaml

batch_size: 8 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
num_workers: 4
pin_memory: True

datasets:
  train_val_test_split: [0.6, 0.2, 0.2]
  main:
    _target_: src.datamodule.components.isar_dataset.ISARDataset
    csv_path: ${paths.data_dir}/isar_dataset.csv
    build_from_raw_data: False
  # can also define train, valid, test, one by one, instead of split from 'main' one...
  # NOTE: make sure you remove the train_val_test_split if costume split is not in use!

  predict:
    dataset1:
      _target_: src.datamodule.components.isar_dataset.ISARDataset
      csv_path: ${paths.data_dir}/isar_dataset.csv
      # csv_path: ${paths.root_dir}data/ISAR/isar_dataset.csv
      build_from_raw_data: False

    # or multiple
    #
    #dataset2:
    #  _target_: src.datamodules....
    #...
